"""initial_tables

Revision ID: 001_initial_tables
Revises: 
Create Date: 2026-03-31 10:59:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建上下文表
    op.create_table('contexts',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.String(length=100), nullable=False),
        sa.Column('context_type', sa.String(length=50), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('ttl', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('access_count', sa.Integer(), nullable=False),
        sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
        sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('embedding_dim', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('priority >= 1 AND priority <= 10', name='check_priority_range'),
        sa.CheckConstraint('ttl >= 0', name='check_ttl_positive')
    )
    
    # 创建上下文表索引
    op.create_index('idx_contexts_session_priority', 'contexts', ['session_id', 'priority'], unique=False)
    op.create_index('idx_contexts_created_at', 'contexts', ['created_at'], unique=False)
    op.create_index('idx_contexts_user_session', 'contexts', ['user_id', 'session_id'], unique=False)
    op.create_index('idx_contexts_type_priority', 'contexts', ['context_type', 'priority'], unique=False)
    op.create_index('idx_contexts_active', 'contexts', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_contexts_context_type'), 'contexts', ['context_type'], unique=False)
    op.create_index(op.f('ix_contexts_id'), 'contexts', ['id'], unique=False)
    op.create_index(op.f('ix_contexts_session_id'), 'contexts', ['session_id'], unique=False)
    op.create_index(op.f('ix_contexts_user_id'), 'contexts', ['user_id'], unique=False)
    
    # 创建上下文历史表
    op.create_table('context_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('context_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('changed_by', sa.String(length=100), nullable=True),
        sa.Column('change_reason', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建上下文历史表索引
    op.create_index('idx_context_history_context_id', 'context_history', ['context_id'], unique=False)
    op.create_index('idx_context_history_created_at', 'context_history', ['created_at'], unique=False)
    op.create_index('idx_context_history_version', 'context_history', ['version'], unique=False)
    
    # 创建上下文统计表
    op.create_table('context_stats',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', sa.String(length=100), nullable=False),
        sa.Column('date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('context_type', sa.String(length=50), nullable=False),
        sa.Column('total_count', sa.Integer(), nullable=False),
        sa.Column('active_count', sa.Integer(), nullable=False),
        sa.Column('avg_priority', sa.Float(), nullable=False),
        sa.Column('avg_access_count', sa.Float(), nullable=False),
        sa.Column('total_access_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id', 'date', 'context_type', name='uq_session_date_type')
    )
    
    # 创建上下文统计表索引
    op.create_index('idx_context_stats_session_id', 'context_stats', ['session_id'], unique=False)
    op.create_index('idx_context_stats_date', 'context_stats', ['date'], unique=False)
    op.create_index('idx_context_stats_type', 'context_stats', ['context_type'], unique=False)
    
    # 创建记忆节点表
    op.create_table('memory_nodes',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('node_type', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('embedding_dim', sa.Integer(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('importance_score', sa.Float(), nullable=False),
        sa.Column('stability_score', sa.Float(), nullable=False),
        sa.Column('relevance_score', sa.Float(), nullable=False),
        sa.Column('access_count', sa.Integer(), nullable=False),
        sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cluster_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('cluster_distance', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('access_count >= 0', name='check_access_count_positive'),
        sa.CheckConstraint('importance_score >= 0.0 AND importance_score <= 1.0', name='check_importance_range'),
        sa.CheckConstraint('stability_score >= 0.0 AND stability_score <= 1.0', name='check_stability_range')
    )
    
    # 创建记忆节点表索引
    op.create_index('idx_memory_nodes_type_importance', 'memory_nodes', ['node_type', 'importance_score'], unique=False)
    op.create_index('idx_memory_nodes_created_at', 'memory_nodes', ['created_at'], unique=False)
    op.create_index('idx_memory_nodes_access_count', 'memory_nodes', ['access_count'], unique=False)
    op.create_index('idx_memory_nodes_cluster_id', 'memory_nodes', ['cluster_id'], unique=False)
    op.create_index('idx_memory_nodes_important', 'memory_nodes', ['importance_score'], unique=False, postgresql_where=sa.text('importance_score >= 0.7'))
    op.create_index(op.f('ix_memory_nodes_id'), 'memory_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_memory_nodes_node_type'), 'memory_nodes', ['node_type'], unique=False)
    
    # 创建节点聚类表
    op.create_table('node_clusters',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('centroid_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('node_count', sa.Integer(), nullable=False),
        sa.Column('avg_importance', sa.Float(), nullable=False),
        sa.Column('avg_stability', sa.Float(), nullable=False),
        sa.Column('cohesion_score', sa.Float(), nullable=False),
        sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['centroid_id'], ['memory_nodes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建节点聚类表索引
    op.create_index('idx_node_clusters_centroid', 'node_clusters', ['centroid_id'], unique=False)
    op.create_index('idx_node_clusters_created_at', 'node_clusters', ['created_at'], unique=False)
    
    # 创建节点版本表
    op.create_table('node_versions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('node_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('changed_by', sa.String(length=100), nullable=True),
        sa.Column('change_reason', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建节点版本表索引
    op.create_index('idx_node_versions_node_id', 'node_versions', ['node_id'], unique=False)
    op.create_index('idx_node_versions_created_at', 'node_versions', ['created_at'], unique=False)
    op.create_index('idx_node_versions_version', 'node_versions', ['version'], unique=False)
    
    # 创建关联关系表
    op.create_table('associations',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('source_node_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('target_node_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('context_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('relation_type', sa.String(length=50), nullable=False),
        sa.Column('weight', sa.Float(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('bidirectional', sa.Boolean(), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['source_node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_node_id', 'target_node_id', 'context_id', 'relation_type', name='uq_source_target_context_relation'),
        sa.CheckConstraint('bidirectional IN (true, false)', name='check_bidirectional'),
        sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
        sa.CheckConstraint('weight >= 0.0 AND weight <= 1.0', name='check_weight_range')
    )
    
    # 创建关联关系表索引
    op.create_index('idx_associations_source_target', 'associations', ['source_node_id', 'target_node_id'], unique=False)
    op.create_index('idx_associations_context_source', 'associations', ['context_id', 'source_node_id'], unique=False)
    op.create_index('idx_associations_relation_weight', 'associations', ['relation_type', 'weight'], unique=False)
    op.create_index('idx_associations_created_at', 'associations', ['created_at'], unique=False)
    op.create_index(op.f('ix_associations_id'), 'associations', ['id'], unique=False)
    op.create_index(op.f('ix_associations_relation_type'), 'associations', ['relation_type'], unique=False)
    
    # 创建关联统计表
    op.create_table('association_stats',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('node_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('relation_type', sa.String(length=50), nullable=False),
        sa.Column('direction', sa.String(length=10), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.Column('avg_weight', sa.Float(), nullable=False),
        sa.Column('avg_confidence', sa.Float(), nullable=False),
        sa.Column('total_weight', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('node_id', 'date', 'relation_type', 'direction', name='uq_node_date_relation_direction')
    )
    
    # 创建关联统计表索引
    op.create_index('idx_association_stats_node_id', 'association_stats', ['node_id'], unique=False)
    op.create_index('idx_association_stats_date', 'association_stats', ['date'], unique=False)
    op.create_index('idx_association_stats_relation_type', 'association_stats', ['relation_type'], unique=False)
    
    # 创建关联模式表
    op.create_table('association_patterns',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('target_type', sa.String(length=50), nullable=False),
        sa.Column('relation_type', sa.String(length=50), nullable=False),
        sa.Column('support', sa.Float(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('lift', sa.Float(), nullable=False),
        sa.Column('occurrence_count', sa.Integer(), nullable=False),
        sa.Column('avg_weight', sa.Float(), nullable=False),
        sa.Column('avg_confidence', sa.Float(), nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建关联模式表索引
    op.create_index('idx_association_patterns_support', 'association_patterns', ['support'], unique=False)
    op.create_index('idx_association_patterns_confidence', 'association_patterns', ['confidence'], unique=False)
    op.create_index('idx_association_patterns_created_at', 'association_patterns', ['created_at'], unique=False)
    
    # 更新记忆节点表的外键约束
    op.create_foreign_key('fk_memory_nodes_cluster_id', 'memory_nodes', 'node_clusters', ['cluster_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除外键约束
    op.drop_constraint('fk_memory_nodes_cluster_id', 'memory_nodes', type_='foreignkey')
    
    # 删除关联模式表
    op.drop_table('association_patterns')
    
    # 删除关联统计表
    op.drop_table('association_stats')
    
    # 删除关联关系表
    op.drop_table('associations')
    
    # 删除节点版本表
    op.drop_table('node_versions')
    
    # 删除节点聚类表
    op.drop_table('node_clusters')
    
    # 删除记忆节点表
    op.drop_table('memory_nodes')
    
    # 删除上下文统计表
    op.drop_table('context_stats')
    
    # 删除上下文历史表
    op.drop_table('context_history')
    
    # 删除上下文表
    op.drop_table('contexts')
    
    # ### end Alembic commands ###